version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/strava-mt-app:latest
    restart: always
    networks:
      - backend
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REDIRECT_URI=${STRAVA_REDIRECT_URI}

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - certs:/etc/ssl/certs:rw
    depends_on:
      - app
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    environment:
      - LETSENCRYPT_DOMAIN
      - LETSENCRYPT_EMAIL
    command: sh -c "certbot certonly --standalone -d $${LETSENCRYPT_DOMAIN} --non-interactive --agree-tos --email $${LETSENCRYPT_EMAIL} --keep-until-expiring && cat /etc/letsencrypt/live/$${LETSENCRYPT_DOMAIN}/fullchain.pem /etc/letsencrypt/live/$${LETSENCRYPT_DOMAIN}/privkey.pem > /etc/letsencrypt/messner.click.pem"
    networks:
      - backend
    depends_on:
      - haproxy
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  certs:
    external: true
