version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/strava-mt-app:latest
    restart: always
    networks:
      - backend
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REDIRECT_URI=${STRAVA_REDIRECT_URI}

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - certs:/etc/ssl/certs:rw
    depends_on:
      - app
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    command: >
      sh -c "certbot certonly --standalone -d multi-track-analyzer.messner.click
      --non-interactive --agree-tos --email your@email.com
      --keep-until-expiring
      && cat /etc/letsencrypt/live/multi-track-analyzer.messner.click/fullchain.pem 
      /etc/letsencrypt/live/multi-track-analyzer.messner.click/privkey.pem > 
      /etc/letsencrypt/messner.click.pem"
    networks:
      - backend
    depends_on:
      - haproxy
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  certs:
    external: true
