services:
  backend:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  aider_full:
    image: paulgauthier/aider-full
    container_name: aider_full
    restart: no
    # Loading the environment file
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - /Users/mesznera/gits/fw_analyzer:/app
      - /Users/mesznera/.gitconfig:/app/.gitconfig:ro
      - /Users/mesznera/.vim:/app/.vim:ro
    # Ensure dependencies are installed or use a pre-built image
